### PR TITLE
navigation functionality improved

### PR DESCRIPTION
**Pull request by BryanNilsen**
Welcome page navigation functionality added > select login or register.
>> Upon submit, user is directed to main dashboard with each category listed.
>> Use main navigation to select category to fill content window
>> Functionality added to "Add" links on each category to show form inputs

### CODE REVIEW

**Review by amazoradi — COMMENTED** [review]
👍 The functionality looks great.  You just worked on the functionality (hide/show) of the app right Bryan? You didnt try and tackle the user session storage, right? 
The functionality changes look and work great on my computer, I just want to make sure that was all this PR was for. If so Big thumbs up.

**Comment by laboyd001** [comment]
👍

**Comment by BryanNilsen** [comment]
Hey, I made a few more changes to this branch and PR. I added the logout and dashboard buttons and adjusted the colors a bit in the CSS.

**Comment by laboyd001** [comment]
Hey Bryan!  This is great!  👍  🦆

**Review by laboyd001 — APPROVED** [review]
👍

**Comment by jessicabarnett8219** [comment]
This looks amazing!! Great job, Bryan! My only request is to change the name from events.js to something like dashboard.js or layout.js. Just anything to distinguish it from the events module since that will have it's own script file too. But no need to wait for another set of ducks to merge haha. 🦆 approved.

**Review by jessicabarnett8219 — APPROVED** [review]
🦆

**Review by jessicabarnett8219 — APPROVED** [review]
👍

**Pull request merged**
