### PR TITLE
can log user id and filter results on events

### PR DESCRIPTION
**Pull request by BryanNilsen**
all categories populating, session storage storing, events filtering

### CODE REVIEW

**Comment by BryanNilsen** [comment]
conflict free, suckas!

**Review by amazoradi — COMMENTED** [review]
🦆

**Review by laboyd001 — APPROVED** [review]
🦆 
I see users!!!

**Comment by jessicabarnett8219** [comment]
💯

**Comment by amazoradi** [comment]
even better

**Comment by laboyd001** [comment]
woo hoo 👍

**Pull request merged**
